name: movlib
description: Aplicativo de filmes desenvolvido para a matéria de Processos de Software

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  http: ^0.12.1
  provider: ^4.3.2+2
  firebase_auth: ^0.18.1+1
  google_sign_in: ^4.5.4
  firebase_core: ^0.5.0
  transparent_image: ^1.0.0
  photo_view: ^0.10.2
  youtube_player_flutter: ^7.0.0+5
  url_launcher: ^5.5.2
  flutter_rating_bar: ^3.0.1+1
  cloud_firestore: ^0.14.1+3
  shared_preferences: ^0.5.12+2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.8.0
  flutter_native_splash: ^0.1.9
  test: ^1.15.4
  mockito: ^4.1.3

# Para modificar a splashScreen do app basta mudar os paths abaixo e executar os comandos:
# flutter packages get
# flutter pub pub run flutter_native_splash:create
flutter_native_splash:
  image: assets/launcher/logo_launcher.png
  color: "#202326"

# Para modificar o icone do app basta mudar os paths abaixo e executar os comandos:
# flutter packages get
# flutter packages pub run flutter_launcher_icons:main
flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/launcher/logo_launcher.png"
  image_path_android: "assets/launcher/logo_launcher.png"
  adaptive_icon_background: "#202326" # Android 8.0 ou acima
  adaptive_icon_foreground: "assets/launcher/logo_launcher.png" # Android 8.0 ou acima

flutter:
  uses-material-design: true

  assets:
    - assets/launcher/
    - assets/images/


  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy-Regular.ttf
        - asset: assets/fonts/Gilroy-Bold.ttf
          weight: 700
        - asset: assets/fonts/Gilroy-Heavy.ttf
          weight: 900
        - asset: assets/fonts/Gilroy-Light.ttf
          weight: 100
        - asset: assets/fonts/Gilroy-Medium.ttf
          weight: 300
